# Generated by Django 6.0.5 on 2026-06-06 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_alter_attendance_options_attendance_created_at_and_more'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField()),
                ('checkin_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('checkin_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkout_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visit_photos/')),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('COMPLETED', 'Completed')], default='CHECKED_IN', max_length=20)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='attendance.attendance')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='customers.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
